### PR TITLE
fix(pages): use correct branch for pages project

### LINKED ISSUE #1516: Cannot reference another mount point
Use case: to work on a new feature for theblog which requires some content change, I need to reference another sharepoint folder with content I can update (to not interfere with the production content).

Steps:
- clone theblog
- create a new "mytestbranch" branch locally
- change the mount point in fstab.yaml to another sharepoint folder ("testfolder")
- copy /en/topics/_taxonomy.docx document in "testfolder"
- make some changes in the document
- hlx up
- request http://localhost:3000/en/topics/_taxonomy.plain.html

-> the document served is not the one from "testfolder"

I did not identify yet where the issue is coming from exactly (if this is the branch not being pushed - mountpoint not up-to-date - or something wrong in our logic but logs are already showing a wrong branch:

```
[hlx] info: simulator proxy: try loading from github first: http://127.0.0.1:64744/raw/helix/github.com--adobe--theblog/mytestbranch/en/topics/_taxonomy.md
[hlx] info: Could not find file at http://127.0.0.1:64744/raw/helix/github.com--adobe--theblog/mytestbranch/helix-markup.yaml
[hlx] info: simulator proxy: http://127.0.0.1:64744/raw/helix/github.com--adobe--theblog/mytestbranch/en/topics/_taxonomy.md does not exist. 404
[hlx] info: simulator proxy: fetch from content proxy https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v1?owner=adobe&repo=theblog&path=%2Fen%2Ftopics%2F_taxonomy.md&ref=master&ignore=github
[hlx] info: simulator proxy: fetch from content proxy https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v1?owner=adobe&repo=theblog&path=%2Fen%2Ftopics%2F_taxonomy.md&ref=master&ignore=github: 200
```

In the last 2 logs (`fetch from content proxy`), `ref` is `master` which is wrong, should be `mytestbranch`. I tried to change that but it does not fix the issue.

cc @tripodsan @trieloff

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #1516

### CODE REVIEW

**Review by trieloff — APPROVED** [review]

**Review by kptdobe — CHANGES_REQUESTED** [review]
I assume if this does not break a test, this means we do not have one covering this use case.

**Comment by tripodsan** [comment]
> I assume if this does not break a test, this means we do not have one covering this use case.

what do you mean?

**Comment by kptdobe** [comment]
Ah sorry... I meant: the test might be missing, no ?

**Comment by tripodsan** [comment]
> Ah sorry... I meant: the test might be missing, no ?

yeah.... it is missing. I can add one.

**Review by kptdobe — APPROVED** [review]
Thanks!

**Pull request merged**
