### PR TITLE
Publish queries

### PR DESCRIPTION
**Pull request by trieloff**
Adds support for https://github.com/adobe/helix-publish/pull/288

### CODE REVIEW

**Comment by trieloff** [comment]
`helix-index.yaml` is read and passed on to `helix-publish`, so that https://github.com/adobe/helix-publish/pull/288 can create proxies for each index/query defined in `helix-index.yaml`.

**Comment by tripodsan** [comment]
> `helix-index.yaml` is read and passed on to `helix-publish`, so that [adobe/helix-publish#288](https://github.com/adobe/helix-publish/pull/288) can create proxies for each index/query defined in `helix-index.yaml`.

ah, ok. but on the long run, this will not work. since the `helix-index.yaml` is defined on a project repository, that might not have its own fastly service.

e.g. _theblog_ defines the helix-index.yaml, but we should not deploy this to helix-pages. and we should also not create an own fastly-service for _theblog_.

so, the helix-pages VCL needs to contain special cases for _all_ projects that use an index...
or we need to start creating a fastly-service for _theblog_ that handles the queries and proxies the rest to helix-pages.

**Comment by trieloff** [comment]
I don't see this as a Helix problem per se (and therefore don't agree with removing the feature from `helix-publish` or blocking the PR in `helix-cli`), but as a Helix Pages problem.

What we can do in Helix Pages is define a couple generic queries and indexes that can be shared by consumers. Helix Pages users can override how these indexes are populated, but not how they are queried.

At a later point in time, we can also add a Runtime-backed query type that will be less efficient in execution than the straight Fastly-Algolia proxy, but I'd start with what we have and improve incrementally.

**Comment by tripodsan** [comment]
> Helix Pages users can override how these indexes are populated, but not how they are queried.

In any case, we need to treat those special. i.e. the name of the index depends on the repository, so for each customer, this name needs to be either passed as url parameter, or it needs to be addressed by a separate service config.

even with this change, since the `helix-index.yaml` is not in the helix-pages repository, but the `theblog` repository, this would not help for theblog. of course it ca be copied there, but this is kind of weird...

I think we should avoid deviating too much from a good solution, just to get _theblog_ to work..

I think a better solution would be to:
- create a fastly service just for theblog (I think we already have one)
- add the special query stuff there
- use the helix-bot to trigger update and cacheflush etc...

**Comment by trieloff** [comment]
> In any case, we need to treat those special. i.e. the name of the index depends on the repository, so for each customer, this name needs to be either passed as url parameter, or it needs to be addressed by a separate service config.

No, the `helix.vcl` uses the `owner` and `repo` for the index name, and that is handled well in the Helix Pages extensions.

I'll provide a suggestion for a generic fallback later, but I'd be glad if we could merge the PR as is

**Pull request merged**
