### PR TITLE
WIP Deploy, content url and default strain fix tentative - still a test falling

### PR DESCRIPTION
**Pull request by kptdobe**
PR for #369 

WIP - still working on making some meaningful non failing tests

### CODE REVIEW

**Comment by kptdobe** [comment]
Tests are all successful with https://github.com/adobe/helix-shared/pull/17
Working on more test cases.

**Comment by trieloff** [comment]
@kptdobe adobe/helix-shared#17 is merged, released, in master and in this branch.

**Comment by trieloff** [comment]
@kptdobe is still still WIP or should we close it?

**Comment by kptdobe** [comment]
I close it since you are changing everything anyway.

**Pull request closed without merging**
