### PR TITLE
Fix Missing Image Optimization

### PR DESCRIPTION
**Pull request by trieloff**
This is work in progress for #340 

@ejthurgo I'll invite you as a reviewer, so you can leave comments in a consolidated place, not commit by commit.

### CODE REVIEW

**Comment by trieloff** [comment]
@ejthurgo I wasn't sure if Image Optimization was enabled at all, so in 722505d I've added it to the debug output. (`X-Debug: true` request header).

```bash
$ curl -v "https://www.primordialsoup.life/big-image.jpg?width=120&auto=webp" \
     -H 'X-Debug: true'
```

and 

```bash
curl -v "https://www.primordialsoup.life/helix_logo.png?width=120&auto=webp" \
     -H 'X-Debug: true'
```

both show the header, but piping it in `file -` tells me that the resizing doesn't happen yet.

**Comment by ejthurgo** [comment]
https://github.com/adobe/helix-cli/commit/722505d11c40f036fed9994c1751307aa045cab8#diff-879237844530beea65db3434a1074f66R428

a) `(req.http.X-Static != "Static") && (req.http.X-Static == "Redirect")`, these conditions seem mutually exclusive. Just checking for redirect should simplify this. however…
b) It seems `X-Static` header is set after `vcl_recv`. Meaning this condition will never be met.

It looks like that change in:
https://github.com/adobe/helix-cli/commit/722505d11c40f036fed9994c1751307aa045cab8
should fix this.

**Comment by trieloff** [comment]
The old block is gone, but I still can't see any traces of the image optimization at work:


Debug response headers for https://www.primordialsoup.life/big-image.jpg?width=120&auto=webp
```
X-XSS-Protection: 1; mode=block
ETag: "4ed40bc0a13210f317384a09ab5abe0a3db7b535"
Content-Type: application/octet-stream
Cache-Control: max-age=300
X-Geo-Block-List:
X-GitHub-Request-Id: 2A4A:1DF6:256F0D:295791:5BF66FD4
Via: 1.1 varnish
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: c93b1d9ada2c736002f311eece7eaf85fff40dbb
Source-Age: 0
X-Backend-Name: 3l2MjGcHgWw5NUJz7OKYH3--F_GitHub
X-CDN-Request-ID: 517a89a5-8acc-4ed0-9e1a-56250801b642
Via: 1.1 varnish
Accept-Ranges: bytes
Age: 293
Content-Length: 7638455
Accept-Ranges: bytes
Date: Thu, 22 Nov 2018 09:03:53 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-iad2120-IAD, cache-iad2134-IAD, cache-lhr6328-LHR
X-Cache: MISS, MISS, HIT
X-Cache-Hits: 0, 0, 0
X-Timer: S1542877434.951802,VS0,VE8
Vary: Accept
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Version: 804; src=804; cli=0.9.2-pre.13; rev=7520ecbecefbc3b958fb1d331db2e9e225aacb00
X-Backend-URL: /trieloff/helix-demo/master/big-image.jpg
X-Branch: master
X-Strain: default
X-Github-Static-Ref: @(null)
X-Action-Root: /trieloff/default/git-github-com-trieloff-helix-demo-git--master--
X-URL: /big-image.jpg?width=120&auto=webp
X-Root-Path: /
X-Fastly-Imageopto-Api: fastly
```

(The `X-Fastly-Imageopto-Api` header is set in the request, I'm just copying the value into the repose for debugging)

**Comment by trieloff** [comment]
As of c5b52c7 and cf09a05 embed processing has been fixed.

**Pull request merged**
