### PR TITLE
use native ES6 Promise

### PR DESCRIPTION
**Pull request by stefan-guggisberg**

### CODE REVIEW

**Comment by trieloff** [comment]
Do we have to replace `request-promise` with `request-promise-native` to make this work?

**Comment by stefan-guggisberg** [comment]
> Do we have to replace request-promise with request-promise-native to make this work?

good point. ideally yes, but removing the direct `bluebird` dependency doesn't break `request-promise` which includes it's own `bluebird` dependency. 

i'll create another PR.

**Comment by stefan-guggisberg** [comment]
i've updated this PR (replace request-promise with request-promise-native(

**Comment by trieloff** [comment]
Fixed #116

**Pull request merged**
