### PR TITLE
feat(up): hlx up defaults to local repo

### LINKED ISSUE #913: --local-repo=. should be default
**Description**
once deployed, the content repo is set to the git origin and the local development uses the remote repository, which is not intuitive.

## suggest

make `--local-repo` the default. if devs want to test the remote content repository, they can specify `--no-local-repo`

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
fix #913

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by tripodsan** [comment]
@stefan-guggisberg I added a commit that adds more tests and removes the `--no-local-repo`  option. this is not required since yargs does this automatically for `--no-*` args

**Comment by stefan-guggisberg** [comment]
> dd test for



> please add test for `--no-local-repo`

there already was a test for `--no-local-repo`: https://github.com/adobe/helix-cli/blob/387ce6e697fc4283947c59a3b16af71c751fef8d/test/testUpCli.js#L212-L218

**Comment by stefan-guggisberg** [comment]
> @stefan-guggisberg I added a commit that adds more tests and removes the `--no-local-repo` option. this is not required since yargs does this automatically for `--no-*` args.

@tripodsan I learned about the automagic support for `--no-*` args the hard way, i.e. I wasted too much time debugging `yargs`. It's not well documented :/

I explicitly added the  `--no-local-repo` option in order to show up on `hlx up --help`.

**Comment by tripodsan** [comment]
> I explicitly added the `--no-local-repo` option in order to show up on `hlx up --help`.

but then we should also add it to the help for `hlx up --no-open`, just to be consistent.

**Comment by stefan-guggisberg** [comment]
regarding the failing smoke test:
https://github.com/adobe/project-helix.io/pull/62

**Pull request merged**
