### PR TITLE
feat(cgi-bin): build and deploy JS files from the cgi-bin folder

### LINKED ISSUE #436: provide cgi like actions
as discussed during the 4/2018 hackathon, we should produce an ability to create cgi-like actions.

- they will be served from in `htdocs/cgi-bin`
- they contain a main function that has the same signature as a pipeline function
- they are similar to the pure actions (#334) but are not bound to a resource but have a url.

for example:

`htdocs/cgi-bin/login.js`

would be invoked with:

`https://demo.project-helix.io/cgi-bin/login.js`

/cc @davidnuescheler

### PR DESCRIPTION
**Pull request by trieloff**
fixes #436 (work in progress)

### CODE REVIEW

**Comment by trieloff** [comment]
@tripodsan do you have an idea why the bundler includes the entire source code in the ZIP file for a dependency-free example file (hello world):

```bash
$ unzip -l .hlx/build/cgi-bin/hello.zip
Archive:  .hlx/build/cgi-bin/hello.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      135  05-09-2019 08:53   package.json
        0  05-09-2019 08:45   node_modules/helix-demo/cgi-bin/
      203  05-09-2019 08:52   hello.js
      158  05-09-2019 08:45   node_modules/helix-demo/cgi-bin/hello.js
        0  04-25-2019 08:22   node_modules/helix-demo/dist/
      921  04-25-2019 08:22   node_modules/helix-demo/dist/favicon.ico
      711  04-25-2019 08:22   node_modules/helix-demo/dist/style.css
        0  04-25-2019 08:22   node_modules/helix-demo/htdocs/
  7638455  04-25-2019 08:22   node_modules/helix-demo/htdocs/big-image.jpg
        0  04-25-2019 08:22   node_modules/helix-demo/htdocs/css/
   210522  04-25-2019 08:22   node_modules/helix-demo/htdocs/css/bulma.css
    85073  04-25-2019 08:22   node_modules/helix-demo/htdocs/css/bulma.css.map
   176514  04-25-2019 08:22   node_modules/helix-demo/htdocs/css/bulma.min.css
      620  04-25-2019 08:22   node_modules/helix-demo/htdocs/index.js
       19  04-25-2019 08:22   node_modules/helix-demo/htdocs/test.json
        0  04-25-2019 08:22   node_modules/helix-demo/htdocs/web_modules/
    23639  05-06-2019 14:54   node_modules/helix-demo/htdocs/web_modules/@barba--core.js
    74035  05-06-2019 14:54   node_modules/helix-demo/htdocs/web_modules/@barba--core.js.map
     1443  05-06-2019 14:54   node_modules/helix-demo/htdocs/web_modules/@barba--prefetch.js
     4026  05-06-2019 14:54   node_modules/helix-demo/htdocs/web_modules/@barba--prefetch.js.map
        0  04-25-2019 08:22   node_modules/helix-demo/src/
     1860  04-25-2019 08:22   node_modules/helix-demo/src/html.htl
     1076  04-25-2019 08:22   node_modules/helix-demo/src/html.pre.js
---------                     -------
  8219410                     23 files
```

**Comment by trieloff** [comment]
This is yet missing equivalents in `helix-publish` and `helix-simulator`.

**Comment by tripodsan** [comment]
> why the bundler includes the entire source code in the ZIP file for a dependency-free example file (hello world):

it always includes the entire package of a dependency. I don't know why 'helix-demo' is a dependency of 'helix-demo' :-)

**Comment by trieloff** [comment]
@tripodsan are you still firmly against this feature or can you see its merits and applications?

**Comment by tripodsan** [comment]
> are you still firmly against this feature or can you see its merits and applications?

LOL

we can add it :-) since we're not using the pipeline here, the change is quite minimal. I only fear that the VLC gets more and more complicated...

**Comment by trieloff** [comment]
I feel confident that we can handle the VCL changes. At least on the first part of the VCL request processing, we have a good structure with the `X-Request-Type` based dispatch.

**Comment by tripodsan** [comment]
there are a lot of unused test-files in the new `integration-cgi-bin` directory... can you remove this, or just move the cgi to the `integration` one?

**Comment by trieloff** [comment]
Changing the globing pattern will change the output directory. In the original integration test, we create `.hlx/build/html.js` for `src/html.htl`. In the cgi-bin test, the created file is `.hlx/build/src/html.js` and I want to make sure both cases are covered.

In addition, at some point we will add support for event listeners (from `event.d`) and index configs (from `index.d`), so I believe a second, slightly bigger integration test folder should be ok.

**Pull request merged**
