### PR TITLE
SetVCL is async, need to wait for result

### PR DESCRIPTION
**Pull request by kptdobe**
PR for https://github.com/adobe/helix-cli/issues/259

### CODE REVIEW

**Comment by kptdobe** [comment]
For whatever reason, the requests do not go through `node-replay`... need to understand what happens.

**Comment by kptdobe** [comment]
I added a breakpoint in the node-replay patch of the request method and it never goes in there. Not sure why it does not work on my env and on the CI (or even how this would have ever worked...)

**Comment by tripodsan** [comment]
I fixed the tests. Probably some API changed and then replay couldn't find the recorded responses.

**Comment by trieloff** [comment]
@tripodsan did you re-record with a fresh service config? It looks like the test coverage has gone down, and this is typically the coverage of the "create everything from scratch" part.

**Comment by kptdobe** [comment]
Yes he did, the service Id has changed.
I checked the coverage report and it says that some lines have been changed in `up.cmd.js` which not true. Very strange.

**Comment by tripodsan** [comment]
> @tripodsan did you re-record with a fresh service config? It looks like the test coverage has gone down, and this is typically the coverage of the "create everything from scratch" part.

yes. I _improved_ the error handling when setting the VLC. I think it might have more lines now. But since we don't have any tests, that cover the error handling, the coverage went down.

see https://github.com/adobe/helix-cli/pull/260/files#diff-64a55b500b78cf4831b3bf2ed1f97953

**Comment by trieloff** [comment]
We could probably copy the fixtures directory, edit some of the responses manually and replay the tests with broken responses to test the error case.

**Pull request merged**
